{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aether-nexus.fullname" . }}-pvc
  labels:
    {{- include "aether-nexus.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClassName | default "standard" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
